#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
# picom --experimental-backends --config ~/.config/picom/picom.conf &
fcitx5 &
~/.config/polybar/launch.sh

xrandr_output=$(bspc query -M --names)
if echo "$xrandr_output" | grep -q "HDMI-A-0" || "$xrandr_output" | grep -q "center";then
	echo "Xft.dpi: 120" | xrdb -merge
	echo "Xcursor.size: 50" | xrdb -merge
	echo "Xcursor.theme: Nordzy-cursors" | xrdb -merge
	feh --bg-center ~/.config/feh/monitor.jpg & # wallpaper
	xrandr --output HDMI-A-0 --primary
	xrandr --output eDP --right-of HDMI-A-0
	xrandr --output eDP --off
	bspc monitor HDMI-A-0 -n center
	bspc monitor eDP -n right
	bspc monitor center -d 1 2 3 4 5 6 7 8 9 10
	# bspc monitor right -d 6 7 8 9 10
else
	echo "Xft.dpi: 200" | xrdb -merge
	echo "Xcursor.size: 70" | xrdb -merge
	echo "Xcursor.theme: Nordzy-cursors" | xrdb -merge
	feh --bg-center ~/.config/feh/note.jpg &
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

# 边框大小
bspc config border_width         	0
# 窗口之间的间隙大小
bspc config window_gap           	10

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		false
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#282828"
bspc config focused_border_color	"#81A1C1"
bspc config urgent_border_color		"#88C0D0"
bspc config presel_border_color		"#8FBCBB"
bspc config presel_feedback_color	"#81A1C1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
